### ISSUE TITLE
Auto approve installation

### ISSUE THREAD

**Issue by alekslyse** [ich777/un-get#12]
I want to install some packages during boot via the script function, how can I for example run un-get install mosh without having to manually say yes? Could it be possible like on apt just be un-get install -y mosh

**Comment by alekslyse** [comment]
actually can be solved with «yes | un-get install mosh»

**Comment by ich777** [comment]
Sorry for the late response but I completely forgot about that Issue here, shame on me...

I have to say that I don't want to change that because this is a pretty low level installation tool for packages and I want to ensure that everyone reads the package list again before installing it and not installing blindly some packages they might even don't want to install, hope that makes sense to you.

As you've already discovered you can circumvent that with `yes`, I hope that's good enough.

**Comment by ich777** [comment]
Closing this issue due to no response. If you have any further questions @alekslyse feel free to re-open or open a new issue.
