### ISSUE TITLE
nvme-cli

### ISSUE THREAD

**Issue by pniewiadowski** [ich777/un-get#15]
I have installed nvme-cli tool using un-get
`un-get install nvme-cli`
but then when I try to run it I got below:
`root@Tower:/# nvme-cli
-bash: nvme-cli: command not found
`
Do you know why?

**Comment by ich777** [comment]
I need more information on this.What Unraid version? What repositories do you have in your sources list? What was the output when installing itI would recommend that you don‘t install nvme-cli anyways because nvme-cli will be built into Unraid itself in an upcoming version.Am 20.12.2023 um 14:30 schrieb pniewiadowski ***@***.***>:﻿
I have installed nvme-cli tool using un-get
un-get install nvme-cli
but then when I try to run it I got below:
***@***.***:/# nvme-cli -bash: nvme-cli: command not found 
Do you know why?

**Comment by pniewiadowski** [comment]
@ich777 you are right. I see it coming in [6.12.6](https://docs.unraid.net/unraid-os/release-notes/6.12.6/#package-updates). Let's close it then. Thanks.
