### ISSUE TITLE
"un-get" is not very convenient to enter, I feel it would be better to change the name. Such as "spkg"

### ISSUE THREAD

**Issue by lalasou** [ich777/un-get#7]
"un-get" is not very convenient to enter, I feel it would be better to change the name. Such as "spkg"

Can you add some more sources? This feels much better than "nerdtools". Thank you.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ich777** [comment]
@lalasou thank you for the recommendation but I won't change that but what you can simply do is create a symbolic link with:
`ln -s /usr/bin/un-get /usr/bin/sget`
(put that command in the go file or in a user script that runs on startup and will afterwards it will be available as `sget` from your terminal)
I hope you understand that and this is a "good enough" workaround for you.

Adding sources is always up to the user, you can add whatever repository you want, as long as it follows the Slackware repository standard. The two repositories which I ship are trusted from my side, this is from Slackware itself and the second from Conraid, I don't want to add other repositories because I don't know if there are maybe malicious packages in there. Hope you understand that too.

BTW recently I got a request for this repo over here: `https://ftp.sotirov-bg.net/pub/contrib/slackware/packages/slackware64-15.0/` in issue #6 because it doesn't followed the Slackware standard but now it's working. Maybe you find packages which you are missing there.

**Comment by lalasou** [comment]
ok   thank you very much
